import { WebsiteCmsConfig } from './website-cms.models';

export const DEFAULT_CMS_CONFIG: WebsiteCmsConfig = {
  lastUpdated: new Date().toISOString(),
  updatedBy: 'system',

  global: {
    siteName: 'SNT Education',
    tagline: 'Empowering Careers',
    logoText: 'SNT',
    logoUrl: '',
    supportEmail: 'mnath.snt@gmail.com',
    supportPhone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    address: 'F-177/4, Flat No. 1, UG/F, Maa Saraswati Apartment, Mehrauli, New Delhi – 110030',
    mapLink: '',
    workingHours: 'Mon–Sat: 9 AM – 7 PM',
    footerDesc: "India's growing IT training & software consultancy network. Empowering students and entrepreneurs since 2011.",
    footerCopyright: '© 2024 SNT Super Net Technologies Pvt. Ltd. All rights reserved.',
    primaryColor: '#6366f1',
    socialLinks: [
      { platform: 'Facebook', url: '#' },
      { platform: 'LinkedIn', url: '#' },
      { platform: 'YouTube',  url: '#' },
    ],
    navItems: [],
    announcementBar: { visible: false, text: '🎉 New batch starting soon! Enroll now.', bgColor: '#6366f1' },
  },

  seo: {
    home:               { metaTitle: 'SNT Education — IT Training & Franchise Network', metaDescription: 'Join 10,000+ students. Industry-aligned IT courses, 95% placement rate, 30+ branches.', ogImageUrl: '', indexed: true },
    about:              { metaTitle: 'About SNT Education — Our Story & Mission',       metaDescription: 'Since 2010, SNT Education has been transforming careers through quality IT training.', ogImageUrl: '', indexed: true },
    contact:            { metaTitle: 'Contact SNT Education',                           metaDescription: 'Get in touch with SNT Education for courses, franchise, or corporate training.', ogImageUrl: '', indexed: true },
    becomePartner:      { metaTitle: 'Become an SNT Franchise Partner',                 metaDescription: 'Own a profitable IT training centre. Low investment, high returns, full support.', ogImageUrl: '', indexed: true },
    courses:            { metaTitle: 'IT Courses at SNT Education',                     metaDescription: 'Explore job-ready IT courses with placement support.', ogImageUrl: '', indexed: true },
    placements:         { metaTitle: 'Placements at SNT Education — 95% Rate',          metaDescription: '10,000+ students placed in top IT companies across India.', ogImageUrl: '', indexed: true },
    careers:            { metaTitle: 'Careers at SNT Education',                        metaDescription: 'Join our team of trainers, managers, and tech professionals.', ogImageUrl: '', indexed: true },
    internships:        { metaTitle: 'Internships at SNT Education',                    metaDescription: 'Apply for IT internships with real project experience.', ogImageUrl: '', indexed: true },
    corporateTraining:  { metaTitle: 'Corporate Training by SNT Education',             metaDescription: 'Upskill your workforce with industry-aligned IT training programs.', ogImageUrl: '', indexed: true },
    collegePartnerships:{ metaTitle: 'College Partnerships — SNT Education',            metaDescription: 'Partner with SNT for campus training, internships, and placement support.', ogImageUrl: '', indexed: true },
    hireTalent:         { metaTitle: 'Hire Talent from SNT Education',                  metaDescription: 'Access job-ready IT graduates from our placement network.', ogImageUrl: '', indexed: true },
    franchise:          { metaTitle: 'SNT Franchise Model — Own an IT Training Centre', metaDescription: 'Low investment, high returns. Join the SNT franchise network.', ogImageUrl: '', indexed: true },
  },

  home: {
    hero: {
      visible: true,
      badgeText: "🏆 India's #1 IT Training Franchise Network",
      title: 'Launch Your Career in IT & Technology',
      subtitle: 'Industry-aligned courses, guaranteed placement support, and a technology platform built for the modern learner. Join 10,000+ students who transformed their careers with SNT.',
      cta1: { label: 'Explore Courses →', link: '/courses', variant: 'primary' },
      cta2: { label: 'Open a Franchise',  link: '/become-a-partner', variant: 'outline' },
      imageUrl: '',
      imageAlign: 'left',
      trustPoints: ['✅ 95% Placement Rate', '✅ 50+ Hiring Partners', '✅ 30+ Branches Nationwide'],
      stats: [
        { icon: '🎓', value: '10,000+', label: 'Students Trained' },
        { icon: '💼', value: '95%',     label: 'Placement Rate' },
        { icon: '🏢', value: '30+',     label: 'Active Branches' },
      ],
    },
    statsBar: {
      visible: true,
      items: [
        { icon: '', value: '10,000+', label: 'Students Placed' },
        { icon: '', value: '50+',     label: 'Hiring Companies' },
        { icon: '', value: '6.5 LPA', label: 'Average Package' },
        { icon: '', value: '95%',     label: 'Placement Rate' },
      ],
    },
    featuresSection: {
      visible: true,
      eyebrow: 'Why Choose SNT',
      title: 'The SNT Advantage',
      items: [
        { icon: '🎯', title: 'Industry-Aligned Curriculum',  desc: 'Courses designed with hiring partners to ensure job-readiness from day one.' },
        { icon: '🖥️', title: 'Advanced LMS Platform',        desc: 'Learn anytime, anywhere with our cloud-based learning management system.' },
        { icon: '🤝', title: 'Placement Guarantee',          desc: 'Dedicated placement cell with 50+ corporate hiring partners across India.' },
        { icon: '👨🏫', title: 'Expert Trainers',             desc: 'Learn from industry professionals with 5–15 years of real-world experience.' },
        { icon: '📜', title: 'Recognized Certification',     desc: 'Earn certificates recognized by top IT companies and verified digitally.' },
        { icon: '🏢', title: 'Pan-India Network',            desc: '30+ branches across India with centralized academic and placement support.' },
      ],
    },
    franchiseCta: {
      visible: true,
      eyebrow: 'Business Opportunity',
      title: 'Own a Profitable IT Training Centre',
      subtitle: "Join SNT's franchise network and build a sustainable education business with our proven model, centralized support, and technology platform.",
      points: [
        '✅ Low investment, high returns',
        '✅ Complete training & onboarding support',
        '✅ Centralized LMS & admin platform',
        '✅ Placement network access',
        '✅ Marketing & brand support',
      ],
      cta1: { label: 'Apply for Franchise →', link: '/become-a-partner', variant: 'primary' },
      cta2: { label: 'Learn More',            link: '/franchise-model',  variant: 'white-outline' },
      stats: [
        { icon: '', value: '30+',  label: 'Active Franchise Branches' },
        { icon: '', value: '₹2L+', label: 'Monthly Revenue Potential' },
        { icon: '', value: '6 Mo', label: 'Average Break-Even Period' },
        { icon: '', value: '98%',  label: 'Partner Satisfaction Rate' },
      ],
    },
    testimonials: {
      visible: true,
      eyebrow: 'Success Stories',
      title: 'Students Who Made It',
      items: [
        { name: 'Priya Sharma',  role: 'Software Engineer', company: 'Infosys', text: "SNT's Full Stack course gave me the skills and confidence to crack my first job at Infosys. The placement support was exceptional." },
        { name: 'Rahul Verma',   role: 'Data Analyst',      company: 'TCS',     text: 'The Python & Data Science course was incredibly practical. I got placed within 2 months of completing the course.' },
        { name: 'Anjali Patel',  role: 'Digital Marketer',  company: 'Wipro',   text: "From zero knowledge to a full-time job in 3 months. SNT's trainers are the best I've encountered." },
      ],
    },
    finalCta: {
      visible: true,
      title: 'Ready to Start Your Journey?',
      subtitle: 'Talk to our counsellors today. Free career guidance session available.',
      cta1: { label: 'Get Free Counselling', link: '/contact',  variant: 'primary' },
      cta2: { label: 'Browse Courses',       link: '/courses',  variant: 'white-outline' },
    },
  },

  about: {
    hero: {
      visible: true,
      badgeText: '🏛️ MCA Registered · CIN: U72200DL2011PTC217571',
      title: 'Transforming Careers Through Technology & Innovation',
      subtitle: 'Incorporated in 2011, SNT Super Net Technologies Pvt. Ltd. is a Delhi-based IT company specialising in software consultancy, custom development, and technology-driven education — empowering students and businesses across India.',
      cta1: { label: '', link: '', variant: 'primary' },
      cta2: { label: '', link: '', variant: 'outline' },
      imageUrl: '',
      imageAlign: 'right',
      trustPoints: [],
      stats: [
        { icon: '', value: '2011', label: 'Incorporated' },
        { icon: '', value: '30+',  label: 'Branches' },
        { icon: '', value: '13+',  label: 'Years Active' },
      ],
    },
    missionVision: {
      visible: true,
      mission: { icon: '🎯', title: 'Our Mission', text: 'To make quality IT education accessible to every student in India, regardless of geography, through our pan-India franchise network and technology-driven learning platform.' },
      vision:  { icon: '🔭', title: 'Our Vision',  text: "To become India's most trusted IT training ecosystem — connecting students to careers, and entrepreneurs to a proven education business model." },
      values:  { icon: '💎', title: 'Our Values',  text: 'Excellence in education, integrity in business, innovation in technology, and commitment to every student\'s career success.' },
    },
    story: {
      visible: true,
      eyebrow: 'Our Story',
      title: 'From a Delhi Startup to a National IT Network',
      paragraphs: [
        'SNT Super Net Technologies Pvt. Ltd. was incorporated on 15 December 2011 under the Ministry of Corporate Affairs (CIN: U72200DL2011PTC217571), headquartered in Mehrauli, New Delhi. Founded with a clear purpose — to bridge the gap between technology education and industry demand.',
        'We operate under NIC code 722, covering software publishing, custom software consultancy, and IT training. Our work spans ready-made software solutions, bespoke application development, and a comprehensive IT education platform designed to produce job-ready professionals.',
        "Our franchise model empowers entrepreneurs across India to run their own SNT-branded IT training centres, backed by our curriculum, LMS platform, placement network, and end-to-end operational support.",
      ],
      ctaLabel: 'Explore Franchise Model →',
      ctaLink: '/franchise-model',
      milestones: [
        { year: '2011', title: 'Company Incorporated',        desc: 'Registered with MCA on 15 Dec 2011, New Delhi. CIN: U72200DL2011PTC217571.' },
        { year: '2013', title: 'IT Training Division Launched', desc: 'Expanded into structured IT education and career placement services.' },
        { year: '2016', title: 'LMS Platform Built',          desc: 'Developed a proprietary cloud-based Learning Management System.' },
        { year: '2019', title: 'Franchise Network Begins',    desc: 'Launched the SNT franchise model — enabling pan-India expansion.' },
        { year: '2022', title: 'Pan-India Presence',          desc: 'Crossed 25 active franchise branches across multiple states.' },
        { year: '2024', title: '30+ Branches · 10K+ Alumni',  desc: 'One of India\'s fastest-growing IT training franchise networks.' },
      ],
    },
    team: {
      visible: true,
      eyebrow: 'Leadership',
      title: 'The Directors Behind SNT',
      members: [
        { name: 'Mahendra Nath Yadav', role: 'Director & Co-Founder', bio: 'Leads technology strategy and business operations at SNT Super Net Technologies. Driving the company\'s vision in IT education and software consultancy since inception.' },
        { name: 'Riti Yadav',          role: 'Director',              bio: 'Oversees organisational governance and strategic partnerships. Instrumental in scaling SNT\'s franchise and education network across India.' },
      ],
    },
    cta: {
      visible: true,
      title: 'Ready to Build Your Future with SNT?',
      cta1: { label: 'Explore Courses',  link: '/courses',          variant: 'primary' },
      cta2: { label: 'Open a Franchise', link: '/become-a-partner', variant: 'outline' },
    },
  },

  contact: {
    visible: true,
    hero: {
      visible: true,
      badgeText: '',
      title: "We'd Love to Hear From You",
      subtitle: "Whether you're a student, corporate client, or franchise aspirant — our team is ready to help.",
      cta1: { label: '', link: '', variant: 'primary' },
      cta2: { label: '', link: '', variant: 'outline' },
      imageUrl: '',
      imageAlign: 'left',
      trustPoints: [],
      stats: [],
    },
    contactItems: [
      { icon: '📧', label: 'Email',           value: 'mnath.snt@gmail.com' },
      { icon: '📞', label: 'Phone',           value: '+91 98765 43210' },
      { icon: '🏢', label: 'Registered Office', value: 'F-177/4, Flat No. 1, UG/F, Maa Saraswati Apartment, Mehrauli, New Delhi – 110030' },
      { icon: '🌐', label: 'Website',         value: 'www.snteducation.com' },
    ],
    officeHours: {
      weekdays: 'Monday – Saturday: 9:00 AM – 7:00 PM',
      sunday:   'Sunday: 10:00 AM – 2:00 PM',
    },
    formTitle: 'Send Us a Message',
  },

  becomePartner: {
    visible: true,
    hero: {
      visible: true,
      badgeText: '',
      title: 'Become an SNT Education Franchise Partner',
      subtitle: 'Fill out the form below and our franchise team will contact you within 24 hours to discuss the opportunity.',
      cta1: { label: '', link: '', variant: 'primary' },
      cta2: { label: '', link: '', variant: 'outline' },
      imageUrl: '',
      imageAlign: 'right',
      trustPoints: [],
      stats: [
        { icon: '', value: '30+',  label: 'Partners' },
        { icon: '', value: '₹2L+', label: 'Revenue' },
        { icon: '', value: '98%',  label: 'Satisfaction' },
      ],
    },
    whyPoints: [
      { icon: '🏷️', label: 'Established Brand' },
      { icon: '🖥️', label: 'Full Tech Platform' },
      { icon: '🤝', label: 'Placement Network' },
      { icon: '💰', label: '₹2L+ Monthly Revenue' },
      { icon: '📞', label: '24hr Support' },
    ],
    nextSteps: [
      { num: '1', title: 'Application Review',    desc: 'Our team reviews your application within 2 hours.' },
      { num: '2', title: 'Franchise Call',         desc: 'A franchise manager calls you within 24 hours.' },
      { num: '3', title: 'Site Visit & Approval',  desc: 'We visit your proposed location and approve.' },
      { num: '4', title: 'Agreement & Launch',     desc: 'Sign agreement, complete setup, and launch!' },
    ],
    quickFacts: [
      { icon: '💰', value: '₹5L+',  label: 'Starting Investment' },
      { icon: '📈', value: '₹2L+',  label: 'Monthly Revenue Potential' },
      { icon: '⏱️', value: '6 Mo',  label: 'Average Break-Even' },
      { icon: '🏢', value: '30+',   label: 'Active Franchise Partners' },
    ],
    contactPhone: 'mnath.snt@gmail.com',
    contactHours: 'Mon–Sat, 9 AM – 7 PM',
  },
};
